### ISSUE TITLE
Production executor entry point broken

### ISSUE THREAD

**Issue by MatthiasBach** [twitter/mysos#56]
The `mysos_executor` entry point references `mysos.executor.mysos_executor:proxy_main`, which does not exist. What is the proper way to get an executor for use outside of vagrant?

**Comment by xujyan** [comment]
@MatthiasBach you are right, `mysos.executor.mysos_executor:proxy_main` doesn't exist here and should be removed.

At Twitter we have a `mysos_executor` implementation and use PEX to package the executor and run it as a binary executable. See <https://github.com/twitter/mysos/blob/3abd54eeb0d59e6c7f4e492864bf8b3151b1f313/tox.ini#L18>.

As we are getting closer to a release we'll add more documentation on this. Thanks for being patient!

**Comment by xujyan** [comment]
Commited c7fb586ec5c9c0bd90471f85a031a4c3bbb379dd to remove the entry point.
