### ISSUE TITLE
add support for adding more instances

### ISSUE THREAD

**Issue by ZeissS** [twitter/mysos#59]
Currently the [docs README](https://github.com/twitter/mysos/blob/master/docs/README.md) talk about being able to scale up and down:

> An elastic solution that allows users to easily scale up and down a MySQL cluster by changing the number of slave instances

But this is neither documented in the user-guide nor part of the `http.py`, so I assume it is missing. We should add it then :)

**Comment by xujyan** [comment]
You are right, this is not implemented. Thanks for raising this issue!

**Comment by xujyan** [comment]
https://issues.apache.org/jira/browse/COTTON-10
